"""Minimal YAML subset reader/writer used by FusionExportSTL.

Bundled inside Fusion 360's script folder so the Fusion-side workflow does
not need PyYAML installed into Fusion's embedded Python.  Also imported by
the trapsim test suite via a direct file-path load.

Supported shape (matches trapsim's geometry.yaml + fusion_map.yaml):
  - top-level dict
  - values: scalar | inline list `[a, b, c]` | nested dict | list of dicts
  - list items begin with `- key: value` and continue with further
    `key: value` lines indented one step further
  - scalars: string (bare or single/double quoted), int, float, true/false, null

Not supported (and rejected): block scalars (`|`, `>`), flow dicts `{}`,
anchors/aliases, multi-document streams, tags, complex keys.
"""

from __future__ import annotations


_INDENT_STEP = 2   # trapsim files are 2-space indented; enforced on read


# ── Public API ────────────────────────────────────────────────────────────────

def parse(text: str):
    """Parse a YAML subset string into a Python dict / list / scalar."""
    tokens = _tokenize(text)
    cursor = [0]
    if not tokens:
        return None
    return _parse_node(tokens, cursor, base_indent=tokens[0][0])


def dump_mapping_file(design_name: str,
                      mappings: list[dict]) -> str:
    """Emit the fixed shape of fusion_map.yaml.

    `mappings` is a list of dicts each with keys 'stl', 'occurrence', 'body'.
    """
    lines = [
        "# fusion_map.yaml — generated by FusionExportSTL, edit at own risk",
        "fusion_design_name: " + _emit_scalar(design_name),
        "mappings:",
    ]
    for m in mappings:
        lines.append("  - stl: "        + _emit_scalar(m["stl"]))
        lines.append("    occurrence: " + _emit_scalar(m["occurrence"]))
        lines.append("    body: "       + _emit_scalar(m["body"]))
    return "\n".join(lines) + "\n"


# ── Tokenizer ─────────────────────────────────────────────────────────────────

def _tokenize(text: str):
    """Return [(indent, content), ...] for non-blank, non-comment lines."""
    out = []
    for raw in text.splitlines():
        line = _strip_line_comment(raw).rstrip()
        if not line.strip():
            continue
        leading = len(line) - len(line.lstrip())
        if "\t" in line[:leading]:
            raise ValueError("tabs not allowed in indentation")
        out.append((leading, line[leading:]))
    return out


def _strip_line_comment(line: str) -> str:
    in_str = False
    quote = ""
    prev = ""
    for i, c in enumerate(line):
        if c in ("'", '"') and prev != "\\":
            if not in_str:
                in_str, quote = True, c
            elif c == quote:
                in_str = False
        elif c == "#" and not in_str:
            return line[:i]
        prev = c
    return line


# ── Recursive parser ──────────────────────────────────────────────────────────

def _parse_node(tokens, cursor, base_indent):
    if cursor[0] >= len(tokens):
        return None
    indent, content = tokens[cursor[0]]
    if indent < base_indent:
        return None
    if content.startswith("- "):
        return _parse_list(tokens, cursor, base_indent)
    return _parse_dict(tokens, cursor, base_indent)


def _parse_dict(tokens, cursor, base_indent):
    result = {}
    while cursor[0] < len(tokens):
        indent, content = tokens[cursor[0]]
        if indent < base_indent:
            break
        if indent > base_indent:
            raise ValueError(
                f"unexpected indent {indent} > {base_indent} at {content!r}")
        if content.startswith("- "):
            raise ValueError(f"list item where dict expected: {content!r}")
        if ":" not in content:
            raise ValueError(f"expected 'key: value', got {content!r}")
        cursor[0] += 1
        key, _, value_str = content.partition(":")
        key = key.strip()
        value_str = value_str.strip()
        if value_str:
            result[key] = _parse_inline(value_str)
        else:
            result[key] = _parse_nested_after_key(tokens, cursor, base_indent)
    return result


def _parse_nested_after_key(tokens, cursor, parent_indent):
    if cursor[0] >= len(tokens):
        return None
    next_indent, next_content = tokens[cursor[0]]
    if next_indent <= parent_indent:
        return None
    # dashes at parent_indent + 0 belong to a list of the parent key
    if next_content.startswith("- ") and next_indent == parent_indent:
        return _parse_list(tokens, cursor, next_indent)
    if next_content.startswith("- "):
        return _parse_list(tokens, cursor, next_indent)
    return _parse_dict(tokens, cursor, next_indent)


def _parse_list(tokens, cursor, base_indent):
    result = []
    while cursor[0] < len(tokens):
        indent, content = tokens[cursor[0]]
        if indent < base_indent:
            break
        if indent > base_indent:
            raise ValueError(
                f"unexpected indent {indent} > {base_indent} in list at {content!r}")
        if not content.startswith("- "):
            break
        cursor[0] += 1
        head = content[2:].strip()
        if not head:
            raise ValueError("empty list item")
        if ":" in head and not head.startswith(("[", '"', "'")):
            # dict-shaped item: first pair inline, remaining pairs at indent+2
            item = {}
            key, _, value_str = head.partition(":")
            key = key.strip()
            value_str = value_str.strip()
            item_indent = base_indent + _INDENT_STEP
            if value_str:
                item[key] = _parse_inline(value_str)
            else:
                item[key] = _parse_nested_after_key(tokens, cursor, item_indent)
            while cursor[0] < len(tokens):
                nind, ncon = tokens[cursor[0]]
                if nind != item_indent or ncon.startswith("- "):
                    break
                if ":" not in ncon:
                    raise ValueError(f"expected 'key: value', got {ncon!r}")
                cursor[0] += 1
                k2, _, v2 = ncon.partition(":")
                k2 = k2.strip()
                v2 = v2.strip()
                if v2:
                    item[k2] = _parse_inline(v2)
                else:
                    item[k2] = _parse_nested_after_key(tokens, cursor, item_indent)
            result.append(item)
        else:
            result.append(_parse_inline(head))
    return result


# ── Inline scalars and lists ──────────────────────────────────────────────────

def _parse_inline(s: str):
    s = s.strip()
    if s.startswith("["):
        if not s.endswith("]"):
            raise ValueError(f"unterminated inline list: {s!r}")
        return _parse_inline_list(s)
    return _parse_scalar(s)


def _parse_inline_list(s: str):
    inner = s[1:-1].strip()
    if not inner:
        return []
    parts, buf, in_str, quote, prev = [], [], False, "", ""
    for c in inner:
        if c in ("'", '"') and prev != "\\":
            if not in_str:
                in_str, quote = True, c
            elif c == quote:
                in_str = False
            buf.append(c)
        elif c == "," and not in_str:
            parts.append("".join(buf).strip())
            buf = []
        else:
            buf.append(c)
        prev = c
    if buf:
        parts.append("".join(buf).strip())
    return [_parse_scalar(p) for p in parts]


def _parse_scalar(s: str):
    if s == "" or s.lower() in ("null", "~"):
        return None
    if s.lower() == "true":
        return True
    if s.lower() == "false":
        return False
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", '"'):
        return _unquote(s)
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    return s


def _unquote(s: str) -> str:
    body = s[1:-1]
    if s[0] == "'":
        return body.replace("''", "'")
    out, i = [], 0
    while i < len(body):
        c = body[i]
        if c == "\\" and i + 1 < len(body):
            nxt = body[i + 1]
            out.append({"n": "\n", "t": "\t", "\\": "\\",
                        '"': '"', "'": "'"}.get(nxt, nxt))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


# ── Emitter (only for fusion_map.yaml) ────────────────────────────────────────

_SAFE_BARE = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                 "0123456789_-./")


def _emit_scalar(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if not isinstance(v, str):
        v = str(v)
    if v == "" or v.lower() in ("null", "true", "false", "~"):
        return _double_quote(v)
    if any(c not in _SAFE_BARE for c in v):
        return _double_quote(v)
    return v


def _double_quote(s: str) -> str:
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + esc + '"'
